### PR TITLE
commit changes from Meng?  I hope all and only the relevant ones

### PR DESCRIPTION
**Pull request by hroskes**
Don't merge yet.  I'm not even sure if it compiles.

I did `git clone` and then copied Meng's directory into mine.  There were a lot of changed files, including some that 
1. had not been changed since the initial commit of this repository, AND also
2. had only trivial changes (like capital C for comment vs. lowercase)

I guess Meng is starting from somewhere else... but I don't know where

I think I got the relevant changes and nothing else, but I have to test it.  Please check yourself also.

### CODE REVIEW

**Comment by usarica** [comment]
Not sure if all of them needed. Can you go over the files that are actually needed? For example, there are changes in chooser, but I intentionally removed line endings/whitespaces. You may jut want to copy lines that are necessary, nothing else.

**Comment by usarica** [comment]
also please open the PR once it compiles.

**Comment by hroskes** [comment]
I'm going to reopen because it's helpful for me to see the diff here.  I'll let you know when I'm satisfied.

**Comment by usarica** [comment]
You can fork and then make the PR once satisfied?

**Pull request closed without merging**
